[versions]
agp = "8.11.2"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"
androidx-activity = "1.11.0"
androidx-appcompat = "1.7.1"
androidx-core = "1.17.0"
androidx-espresso = "3.7.0"
androidx-lifecycle = "2.8.7"
androidx-testExt = "1.3.0"
composeMultiplatform = "1.9.0"
junit = "4.13.2"
kotlin = "2.2.20"
spotless = "8.0.0"
ktlint = "1.0.0"
ktlint-rules = "0.4.25"
kotbase = "3.2.4-1.2.0"
kmp-nativecoroutines = "1.0.0-ALPHA-48"
ksp = "2.2.20-2.0.2"
koin = "4.1.0"import org.jetbrains.kotlin.gradle.dsl.JvmTarget



plugins {
alias(libs.plugins.kotlinMultiplatform)
alias(libs.plugins.spotless)
alias(libs.plugins.kmp.nativecoroutines)
alias(libs.plugins.ksp)
alias(libs.plugins.kotlinx.serialization)
alias(libs.plugins.composeMultiplatform)
alias(libs.plugins.composeCompiler)
}

kotlin {

applyDefaultHierarchyTemplate()

compilerOptions {
freeCompilerArgs.add("-Xexpect-actual-classes")
}
//    androidTarget {
//        compilerOptions {
//            jvmTarget.set(JvmTarget.JVM_11)
//        }
//    }

iosArm64 {
binaries {
framework {
baseName = "Shared"
isStatic = true
binaryOption("bundleId", "com.gmg.growmygarden.shared")
val path = "$rootDir/vendor/CouchbaseLite/CouchbaseLite.xcframework/ios-arm64"
linkerOpts("-F$path", "-framework", "CouchbaseLite", "-rpath", path)
export(libs.androidx.lifecycle.viewmodel)
export(libs.kmp.observableviewmodel.core)
}

getTest("DEBUG").apply {
val path = "$rootDir/vendor/CouchbaseLite.xcframework/ios-arm64_x86_64-simulator"
linkerOpts("-F$path", "-framework", "CouchbaseLite", "-rpath", path)
}
}
}

iosSimulatorArm64 {
binaries {
framework {
baseName = "Shared"
val path = "$rootDir/vendor/CouchbaseLite/CouchbaseLite.xcframework/ios-arm64_x86_64-simulator"
isStatic = true
binaryOption("bundleId", "com.gmg.growmygarden.shared")
linkerOpts("-F$path", "-framework", "CouchbaseLite", "-rpath", path)
export(libs.androidx.lifecycle.viewmodel)
export(libs.kmp.observableviewmodel.core)
}
getTest("DEBUG").apply {
val path = "$rootDir/vendor/CouchbaseLite.xcframework/ios-arm64_x86_64-simulator"
linkerOpts("-F$path", "-framework", "CouchbaseLite", "-rpath", path)
}
}
}

sourceSets {
all {
languageSettings.optIn("kotlinx.cinterop.ExperimentalForeignApi")
languageSettings.optIn("kotlin.experimental.ExperimentalObjCName")
languageSettings.optIn("kotlin.experimental.ExperimentalNativeApi")
languageSettings.optIn("kotlin.uuid.ExperimentalUuidApi")
}
commonMain.dependencies {
// put your Multiplatform dependencies here
implementation(libs.kotbase.ktx)
implementation(libs.koin.core)
implementation(libs.koin.compose)
implementation(libs.kotlinx.serialization.json)
implementation(libs.filekit.core)
implementation(libs.filekit.dialogs)
api(libs.androidx.lifecycle.viewmodel)
api(libs.kmp.observableviewmodel.core)
implementation(libs.alarmee)
implementation("io.ktor:ktor-client-core:2.3.5")
implementation("io.ktor:ktor-client-content-negotiation:2.3.5")
implementation("io.ktor:ktor-serialization-kotlinx-json:2.3.5")
}
commonTest.dependencies {
implementation(libs.kotlin.test)
implementation(libs.koin.core)
implementation(libs.koin.test)
implementation(libs.androidx.coroutine.test)
implementation(libs.moko.permissions.test)
}

iosMain.dependencies {
api(libs.kmp.observableviewmodel.core)
implementation("io.ktor:ktor-client-darwin:2.3.5")
}
iosTest.dependencies {
implementation(libs.alarmee)
api(libs.moko.permissions)
implementation(libs.moko.permissions.notifications)
api(libs.moko.permissions.compose)

}

}
}

tasks.withType<AbstractTestTask> {
testLogging {
events("passed", "skipped", "failed", "standardOut", "standardError")
exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
showExceptions = true
showCauses = false
showStackTraces = false
}
}

spotless {
kotlin {
target("src/**/*.kt")
targetExclude("build/**/*.kt")
targetExclude("src/androidMain/**/*.kt")
// version, editorConfigPath, editorConfigOverride and customRuleSets are all optional
ktlint(libs.versions.ktlint.asProvider().get()).editorConfigOverride(
mapOf(
"indent_size" to 4,
// intellij_idea is the default style we preset in Spotless, you can override it referring to https://pinterest.github.io/ktlint/latest/rules/code-styles.
"ktlint_code_style" to "intellij_idea",
)
).customRuleSets(
listOf(
libs.ktlint.rules.get().toString()
)
)
}
}

//android {
//    namespace = "com.gmg.growmygarden.shared"
//    compileSdk = libs.versions.android.compileSdk.get().toInt()
//    compileOptions {
//        sourceCompatibility = JavaVersion.VERSION_11
//        targetCompatibility = JavaVersion.VERSION_11
//    }
//    defaultConfig {
//        minSdk = libs.versions.android.minSdk.get().toInt()
//    }
//}

kotlinx-serialization-json = "1.9.0"
observableviewmodel = "1.0.0"
androidx-coroutine-test = "1.10.2"
compose = "1.6.5"
alarmee = "2.4.0"
moko = "0.20.1"
filekit = "0.12.0"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-testExt-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-testExt" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-coroutine-test = {module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "androidx-coroutine-test"}
ktlint-rules = { module = "io.nlopez.compose.rules:ktlint", version.ref = "ktlint-rules" }
kotbase-ktx = { module = "dev.kotbase:couchbase-lite-ktx", version.ref = "kotbase" }
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin"}
koin-test = { group = "io.insert-koin", name = "koin-test", version.ref = "koin"}
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json"}
kmp-observableviewmodel-core = {module = "com.rickclephas.kmp:kmp-observableviewmodel-core", version.ref = "observableviewmodel"}
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
alarmee = { group = "io.github.tweener", name = "alarmee", version.ref = "alarmee" }
moko-permissions = {group = "dev.icerock.moko", name = "permissions", version.ref = "moko"}
moko-permissions-test = {group = "dev.icerock.moko", name = "permissions-test", version.ref = "moko"}
moko-permissions-notifications = {group = "dev.icerock.moko", name = "permissions-notifications", version.ref = "moko"}
moko-permissions-compose = {group = "dev.icerock.moko", name = "permissions-compose", version.ref = "moko"}

filekit-core = { group = "io.github.vinceglb", name = "filekit-core", version.ref = "filekit"}
filekit-dialogs = { group = "io.github.vinceglb", name = "filekit-dialogs", version.ref = "filekit"}



[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kmp-nativecoroutines = { id = "com.rickclephas.kmp.nativecoroutines", version.ref = "kmp-nativecoroutines"}
kotlinx-serialization = {id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
