name: Run Tests
on:
  workflow_call:
    inputs:
      shouldRunKmp:
        required: true
        type: string
      shouldRunAndroid:
        required: true
        type: string
      shouldRunIos:
        required: true
        type: string
      shouldRunDesktop:
        required: true
        type: string
env:
  XCODE_VERSION: 'latest-stable'
  JAVA_VERSION: '21'
jobs:
  iOS:
#    if: ${{ inputs.shouldRunKmp == 'true' || inputs.shouldRunIos == 'true' }}
    if: false
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Job set up
        uses: ./.github/actions/job-setup
        with:
          perenual_api_key: ${{ secrets.PERENUAL_API_KEY }}

      - name: iOS set up
        uses: ./.github/actions/ios-setup
        with:
          firebase-plist: ${{ secrets.FIREBASE_PLIST }}

      - run: xcodebuild build test -project iosApp/iosApp.xcodeproj -configuration Debug -scheme iosApp -sdk iphoneos -destination name='iPhone 16' -verbose

  iOS-Test-KMP:
    runs-on: macos-14
    if: ${{ inputs.shouldRunKmp }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/job-setup
        with:
          perenual_api_key: ${{ secrets.PERENUAL_API_KEY }}

      - name: Add Secrets
        shell: bash
        run: |
          cat <<EOF > iosApp/iosApp/Secrets.plist
            <?xml version="1.0" encoding="UTF-8"?>
            <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
             "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
            <plist version="1.0">
            <dict>
                <key>PERENUAL_API_KEY</key>
                <string>${{secrets.PERENUAL_API_KEY}}</string>
            </dict>
            </plist>
          EOF
      - name: Run Tests
        run: ./gradlew clean iosSimulatorArm64Test -p shared
