name: Run Tests
on:
  workflow_call:
    inputs:
      shouldRunKmp:
        required: true
        type: string
      shouldRunAndroid:
        required: true
        type: string
      shouldRunIos:
        required: true
        type: string
      shouldRunDesktop:
        required: true
        type: string
env:
  JAVA_VERSION: '21'
jobs:
  iOS:
#    if: ${{ inputs.shouldRunKmp == 'true' || inputs.shouldRunIos == 'true' }}
    if: false
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Job set up
        uses: ./.github/actions/job-setup

      - name: iOS set up
        uses: ./.github/actions/ios-setup
        with:
          firebase-plist: ${{ secrets.FIREBASE_PLIST }}

      - run: xcodebuild build test -project iosApp/iosApp.xcodeproj -configuration Debug -scheme iosApp -sdk iphoneos -destination name='iPhone 16' -verbose

  iOS-Test-KMP:
    runs-on: macos-14
    if: ${{ inputs.shouldRunKmp }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/job-setup
#      - name: Select Xcode
#        run: sudo xcode-select -s /Applications.Xcode_15.4.app
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'
      - name: Run Tests
        run: ./gradlew clean iosSimulatorArm64Test -p shared